const PROPERTY_CATEGORIES = [
  "상가임대",
  "상가매매",
  "상가주택매매",
  "상가건물매매",
  "토지매매",
  "원룸건물매매",
  "공장·창고",
  "기타"
];

const MOCK_PROPERTIES = [
  {
    id: "P-2026-001",
    property_no: "CA-2601",
    title: "두정동 대로변 1층 상가 임대",
    category: "상가임대",
    deal_type: "월세",
    region: "천안시 서북구 두정동",
    address: "충청남도 천안시 서북구 두정동 중심상권",
    deposit: "3,000만원",
    monthly_rent: "180만원",
    sale_price: "-",
    premium: "협의",
    maintenance_fee: "월 15만원",
    contract_area: "82.6㎡",
    exclusive_area: "66.1㎡",
    floor: "1층",
    total_floor: "5층",
    direction: "남향",
    parking: "인근 공영주차장",
    elevator: "없음",
    move_in_date: "협의",
    approval_date: "2016-08-12",
    building_use: "제2종 근린생활시설",
    zoning: "일반상업지역",
    current_business: "공실",
    recommended_business: "카페, 디저트, 소형 음식점",
    short_description: "유동인구가 꾸준한 두정동 핵심 동선의 1층 점포입니다.",
    description: "대로변 노출과 보행 접근성이 좋아 초도 인지도를 만들기 쉬운 상가입니다. 점포 전면 활용도가 높고 주변 주거·직장 수요가 함께 형성되어 있습니다.",
    broker_comment: "초기 창업자는 권리금과 월 고정비 균형을 함께 검토하는 것이 좋습니다.",
    badges: ["추천", "계약가능"],
    image_url: "images/korea-street-flow.jpg",
    is_featured: true,
    is_urgent: false,
    is_available: true,
    price_sort: 180,
    area_sort: 66.1,
    created_at: "2026-06-21"
  },
  {
    id: "P-2026-002",
    property_no: "CA-2602",
    title: "불당동 신도심 코너 상가 매매",
    category: "상가매매",
    deal_type: "매매",
    region: "천안시 서북구 불당동",
    address: "충청남도 천안시 서북구 불당동 상업지",
    deposit: "-",
    monthly_rent: "임대중",
    sale_price: "8억 9,000만원",
    premium: "-",
    maintenance_fee: "실사용 기준",
    contract_area: "118.8㎡",
    exclusive_area: "94.2㎡",
    floor: "2층",
    total_floor: "7층",
    direction: "동향",
    parking: "건물 내 가능",
    elevator: "있음",
    move_in_date: "임차인 승계",
    approval_date: "2019-11-04",
    building_use: "근린생활시설",
    zoning: "준주거지역",
    current_business: "학원",
    recommended_business: "학원, 병의원, 전문 서비스",
    short_description: "신도심 배후수요와 임차 안정성을 함께 검토할 수 있는 매매 물건입니다.",
    description: "불당동 주거 배후와 생활 편의 수요가 연결되는 위치입니다. 현 임차 업종과 계약 조건을 바탕으로 수익률과 공실 리스크를 함께 검토해야 합니다.",
    broker_comment: "투자 목적이라면 임차인 안정성, 재계약 가능성, 주변 신규 공급을 함께 봐야 합니다.",
    badges: ["추천", "계약가능"],
    image_url: "images/premium/premium-commercial-space.jpg",
    is_featured: true,
    is_urgent: false,
    is_available: true,
    price_sort: 89000,
    area_sort: 94.2,
    created_at: "2026-06-19"
  },
  {
    id: "P-2026-003",
    property_no: "CA-2603",
    title: "신부동 터미널 인근 상가주택 매매",
    category: "상가주택매매",
    deal_type: "매매",
    region: "천안시 동남구 신부동",
    address: "충청남도 천안시 동남구 신부동",
    deposit: "임대 내역 확인",
    monthly_rent: "임대 내역 확인",
    sale_price: "12억 5,000만원",
    premium: "-",
    maintenance_fee: "자체 관리",
    contract_area: "대지 214㎡",
    exclusive_area: "연면적 396㎡",
    floor: "전층",
    total_floor: "4층",
    direction: "남동향",
    parking: "가능",
    elevator: "없음",
    move_in_date: "협의",
    approval_date: "2012-05-17",
    building_use: "근린생활시설 및 단독주택",
    zoning: "일반상업지역",
    current_business: "1층 상가, 상층 주거",
    recommended_business: "임대수익형 보유, 리모델링 검토",
    short_description: "상가와 주거 임대수익을 함께 검토할 수 있는 복합 매물입니다.",
    description: "터미널 생활권과 도심 접근성이 장점입니다. 층별 임대 조건과 향후 수선 비용을 함께 확인해야 안정적인 보유 전략을 세울 수 있습니다.",
    broker_comment: "상가주택은 현재 수익뿐 아니라 건물 관리 상태와 향후 보수비를 반드시 같이 봅니다.",
    badges: ["계약가능"],
    image_url: "images/korea-commercial-building.jpg",
    is_featured: false,
    is_urgent: false,
    is_available: true,
    price_sort: 125000,
    area_sort: 396,
    created_at: "2026-06-17"
  },
  {
    id: "P-2026-004",
    property_no: "CA-2604",
    title: "성정동 수익형 상가건물 매매",
    category: "상가건물매매",
    deal_type: "매매",
    region: "천안시 서북구 성정동",
    address: "충청남도 천안시 서북구 성정동",
    deposit: "임대차 승계",
    monthly_rent: "월 620만원",
    sale_price: "18억원",
    premium: "-",
    maintenance_fee: "임차인 부담",
    contract_area: "대지 327㎡",
    exclusive_area: "연면적 684㎡",
    floor: "전층",
    total_floor: "5층",
    direction: "서향",
    parking: "가능",
    elevator: "있음",
    move_in_date: "임대차 승계",
    approval_date: "2014-03-24",
    building_use: "근린생활시설",
    zoning: "일반상업지역",
    current_business: "음식점, 사무실",
    recommended_business: "수익형 보유, 리뉴얼 임대",
    short_description: "임대차 구조와 공실 리스크를 동시에 살펴볼 수 있는 건물 매매입니다.",
    description: "상층부 임대 안정성과 1층 업종 경쟁력을 함께 검토해야 하는 수익형 건물입니다. 임차인별 계약 기간과 관리비 구조 확인이 필요합니다.",
    broker_comment: "건물 매매는 가격보다 임대차 질과 공실 대응력이 먼저입니다.",
    badges: ["급매", "계약가능"],
    image_url: "images/premium/premium-asset-review.jpg",
    is_featured: true,
    is_urgent: true,
    is_available: true,
    price_sort: 180000,
    area_sort: 684,
    created_at: "2026-06-20"
  },
  {
    id: "P-2026-005",
    property_no: "CA-2605",
    title: "백석동 개발축 인근 토지 매매",
    category: "토지매매",
    deal_type: "매매",
    region: "천안시 서북구 백석동",
    address: "충청남도 천안시 서북구 백석동",
    deposit: "-",
    monthly_rent: "-",
    sale_price: "평당 680만원",
    premium: "-",
    maintenance_fee: "-",
    contract_area: "1,284㎡",
    exclusive_area: "1,284㎡",
    floor: "-",
    total_floor: "-",
    direction: "도로 접면 확인",
    parking: "계획 가능",
    elevator: "-",
    move_in_date: "즉시",
    approval_date: "-",
    building_use: "토지",
    zoning: "계획관리지역",
    current_business: "나대지",
    recommended_business: "창고, 근린시설, 장기 보유",
    short_description: "도로 접근성과 개발 방향을 함께 검토해야 하는 토지 매물입니다.",
    description: "토지는 현재 상태보다 진입 동선, 도로 접면, 용도지역, 인허가 가능성을 중심으로 봐야 합니다. 주변 개발 흐름과 장기 보유 전략이 중요합니다.",
    broker_comment: "토지 매수 전에는 토지이용계획과 건축 가능성을 먼저 확인해야 합니다.",
    badges: ["계약가능"],
    image_url: "images/premium/premium-street-grid.jpg",
    is_featured: false,
    is_urgent: false,
    is_available: true,
    price_sort: 680,
    area_sort: 1284,
    created_at: "2026-06-15"
  },
  {
    id: "P-2026-006",
    property_no: "CA-2606",
    title: "쌍용동 원룸건물 매매",
    category: "원룸건물매매",
    deal_type: "매매",
    region: "천안시 서북구 쌍용동",
    address: "충청남도 천안시 서북구 쌍용동",
    deposit: "임대차 승계",
    monthly_rent: "월 480만원",
    sale_price: "13억 8,000만원",
    premium: "-",
    maintenance_fee: "자체 관리",
    contract_area: "대지 246㎡",
    exclusive_area: "연면적 512㎡",
    floor: "전층",
    total_floor: "4층",
    direction: "남향",
    parking: "일부 가능",
    elevator: "없음",
    move_in_date: "임대차 승계",
    approval_date: "2011-09-08",
    building_use: "다가구주택",
    zoning: "제2종 일반주거지역",
    current_business: "원룸 임대",
    recommended_business: "임대수익형 보유",
    short_description: "월세 현금흐름과 관리 상태를 함께 확인해야 하는 원룸 건물입니다.",
    description: "대학·직장 수요 접근성이 있으며, 공실률과 세대별 계약 조건 확인이 필요합니다. 향후 수선비와 관리 난이도를 함께 검토해야 합니다.",
    broker_comment: "원룸건물은 실수익률 산정 시 공실과 수선 비용을 보수적으로 반영해야 합니다.",
    badges: ["계약가능"],
    image_url: "images/korea-business-front.jpg",
    is_featured: false,
    is_urgent: false,
    is_available: true,
    price_sort: 138000,
    area_sort: 512,
    created_at: "2026-06-13"
  },
  {
    id: "P-2026-007",
    property_no: "CA-2607",
    title: "직산 산업단지 인근 공장·창고 임대",
    category: "공장·창고",
    deal_type: "임대",
    region: "천안시 서북구 직산읍",
    address: "충청남도 천안시 서북구 직산읍",
    deposit: "5,000만원",
    monthly_rent: "350만원",
    sale_price: "-",
    premium: "-",
    maintenance_fee: "협의",
    contract_area: "496㎡",
    exclusive_area: "430㎡",
    floor: "1층",
    total_floor: "1층",
    direction: "북동향",
    parking: "대형차 진입 가능",
    elevator: "없음",
    move_in_date: "즉시",
    approval_date: "2018-12-03",
    building_use: "창고시설",
    zoning: "준공업지역",
    current_business: "창고",
    recommended_business: "물류, 제조 보관, 자재 창고",
    short_description: "차량 진입과 적재 동선이 중요한 공장·창고 임대 매물입니다.",
    description: "산업단지 접근성이 좋고 1층 단독 활용이 가능한 구조입니다. 전력, 층고, 차량 회전 반경은 현장에서 확인하는 것이 좋습니다.",
    broker_comment: "공장·창고는 면적보다 진입 동선과 작업 효율을 먼저 봐야 합니다.",
    badges: ["급매", "계약가능"],
    image_url: "images/premium/premium-blueprint-review.jpg",
    is_featured: false,
    is_urgent: true,
    is_available: true,
    price_sort: 350,
    area_sort: 430,
    created_at: "2026-06-18"
  },
  {
    id: "P-2026-008",
    property_no: "CA-2608",
    title: "천안역 생활권 소형 사무실 임대",
    category: "기타",
    deal_type: "월세",
    region: "천안시 동남구 대흥동",
    address: "충청남도 천안시 동남구 대흥동",
    deposit: "1,000만원",
    monthly_rent: "75만원",
    sale_price: "-",
    premium: "없음",
    maintenance_fee: "월 8만원",
    contract_area: "46.2㎡",
    exclusive_area: "38.5㎡",
    floor: "3층",
    total_floor: "6층",
    direction: "남서향",
    parking: "협의",
    elevator: "있음",
    move_in_date: "즉시",
    approval_date: "2010-04-19",
    building_use: "업무시설",
    zoning: "일반상업지역",
    current_business: "공실",
    recommended_business: "사무실, 예약제 상담실",
    short_description: "초기 고정비를 낮추고 접근성을 확보하기 좋은 소형 공간입니다.",
    description: "천안역 생활권에 위치한 소형 업무 공간입니다. 예약제 상담, 사무실, 소규모 서비스업에 적합하며 관리비와 접근성 균형이 좋습니다.",
    broker_comment: "작게 시작하는 업종은 고정비와 접근성의 균형이 가장 중요합니다.",
    badges: ["계약가능"],
    image_url: "images/premium/premium-contract-desk.jpg",
    is_featured: false,
    is_urgent: false,
    is_available: true,
    price_sort: 75,
    area_sort: 38.5,
    created_at: "2026-06-12"
  }
];

function getMockProperties() {
  return MOCK_PROPERTIES.map((item) => ({ ...item, badges: [...item.badges] }));
}

window.PropertyService = {
  categories: PROPERTY_CATEGORIES,
  getProperties: getMockProperties
};
